# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |docker|
  docker.vm.box = "ubuntu/xenial64"
  docker.vm.hostname = "docker"
  docker.vm.network "private_network", ip:"192.168.60.101"
  docker.vm.synced_folder "sync", "/home/vagrant/sync"

  # Create forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine.
  # NOTE: This will enable public access to the opened ports
  docker.vm.network "forwarded_port", guest:25, host:25, auto_correct: true
  docker.vm.network "forwarded_port", guest:143, host:143, auto_correct: true
  for i in 32760..32780
    docker.vm.network :forwarded_port, guest: i, host: i
  end

  docker.vm.provider "virtualbox" do |vb|
     vb.memory = "2048"
     vb.name = "lb2_docker"
  end

  # Docker Provisioner
  docker.vm.provision "docker" do |d|
   d.pull_images "debian:stretch"
  end

  docker.vm.provision "shell", inline: <<-SHELL
    sudo curl -L "https://github.com/docker/compose/releases/download/1.24.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
  SHELL
end
