Vagrant.configure(2) do |config|
  config.vm.define "mail_server_1" do |ms1|
    ms1.vm.box = "ubuntu/xenial64"
    ms1.vm.hostname = "mail_server_1_hostname"
    ms1.vm.network "forwarded_port", guest: 80, host: 8080
    ms1.vm.network "private_network", ip: "192.168.50.5"
    ms1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mail_server_1"
    end
    # mit diesem abschnitt bringen wir die VM auf den eusten stand
    ms1.vm.provision "shell", inline: <<-SHELL
      # install programm
      sudo apt update
      sudo apt upgrade -y
      sudo apt dist-upgrade -y
      SHELL
    # nach den aktualisierungen muss die vm reloaded werden,
    # um eien möglichen reboot nach den aktualisierungen durchzuführen
    config.vm.provision :reload
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get -y install ntp
      SHELL
  end

  config.vm.define "mail_server_2" do |ms1|
    ms2.vm.box = "ubuntu/xenial64"
    ms2.vm.hostname = "mail_server_2_hostname"
    ms1.vm.network "forwarded_port", guest: 80, host: 9080
    ms2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mail_server_2"
    end
    # mit diesem abschnitt bringen wir die VM auf den eusten stand
    ms2.vm.provision "shell", inline: <<-SHELL
      # install programm
      sudo apt update
      sudo apt upgrade -y
      sudo apt dist-upgrade -y
      SHELL
    # nach den aktualisierungen muss die vm reloaded werden,
    # um eien möglichen reboot nach den aktualisierungen durchzuführen
    config.vm.provision :reload
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get -y install ntp
      SHELL
  end
