Vagrant.configure(2) do |config|
  # define our first vm, named mail-server-1
  config.vm.define "mail-server-1" do |ms1|
    # define the needed infomation, so that the vm can get created
    ms1.vm.box = "ubuntu/xenial64"
    ms1.vm.hostname = "mail-server-1-hostname"
    ms1.vm.network "private_network", ip: "192.168.50.100"
    ms1.vm.network "forwarded_port", guest: 80, host: 8080
    # here we define the physical propertys of the vm
    ms1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mail_server_1"
    end
    # mit diesem abschnitt bringen wir die VM auf den eusten stand
    ms1.vm.provision "shell", inline: <<-SHELL
      debconf-set-selections <<< "postfix postfix/mailname string meuthak.ch"
      debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
      sudo apt-get -y install postfix mailx
      sudo sed -i "s;mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128;mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 0.0.0.0/0;g" /etc/postfix/main.cf
      sudo useradd blub
      echo "localhost   meuthak.ch" >> /etc/hosts
      echo "192.168.50.101   anderedomain.ch" >> /etc/hosts
      SHELL
  end

  # the second vm gets defined with a different name
  config.vm.define "mail-server-2" do |ms2|
    # again, the needed information
    ms2.vm.box = "ubuntu/xenial64"
    ms2.vm.hostname = "mail-server-2-hostname"
    ms2.vm.network "private_network", ip: "192.168.50.101"
    ms2.vm.network "forwarded_port", guest: 80, host: 9080
    # the physical propertys
    ms2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mail_server_2"
    end
    # mit diesem abschnitt bringen wir die VM auf den eusten stand
    ms2.vm.provision "shell", inline: <<-SHELL
      debconf-set-selections <<< "postfix postfix/mailname string meuthak.ch"
      debconf-set-selections <<< "postfix postfix/main_mailer_type string 'Internet Site'"
      sudo apt-get -y install postfix mailx
      sudo sed -i "s;mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128;mynetworks = 127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 0.0.0.0/0;g" /etc/postfix/main.cf
      sudo useradd blub
      echo "localhost   anderedomain.ch" >> /etc/hosts
      echo "192.168.50.10   meuthak.ch" >> /etc/hosts
      SHELL
  end
end
