Vagrant.configure(2) do |config|
  # define our first vm, named mail-server-1
  config.vm.define "mail-server-1" do |ms1|
    # define the needed infomation, so that the vm can get created
    ms1.vm.box = "ubuntu/xenial64"
    ms1.vm.hostname = "mail-server-1-hostname"
    ms1.vm.network "private_network", ip: "192.168.50.100"
    ms1.vm.network "forwarded_port", guest: 80, host: 8080
    # here we define the physical propertys of the vm
    ms1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.name = "mail_server_1"
    end
  end
end
